Document: spring-batch-admin-geoknow
Title: Debian spring-batch-admin-geoknow Manual
Author: <insert document author here>
Abstract: This manual describes what spring-batch-admin-geoknow is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spring-batch-admin-geoknow/spring-batch-admin-geoknow.sgml.gz

Format: postscript
Files: /usr/share/doc/spring-batch-admin-geoknow/spring-batch-admin-geoknow.ps.gz

Format: text
Files: /usr/share/doc/spring-batch-admin-geoknow/spring-batch-admin-geoknow.text.gz

Format: HTML
Index: /usr/share/doc/spring-batch-admin-geoknow/html/index.html
Files: /usr/share/doc/spring-batch-admin-geoknow/html/*.html
